services:
  figuremind-backend:
    network_mode: host
    ports: !reset []

  figuremind-frontend:
    network_mode: host
    ports: !reset []

  figuremind-sam3:
    network_mode: host
    ports: !reset []
